// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Core.Data;

#nullable disable

namespace WeatherApp.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("WeatherApp.Core.Entities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLastSelected")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsLastSelected")
                        .HasDatabaseName("IX_Cities_IsLastSelected");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cities_Name");

                    b.HasIndex("Name", "Country")
                        .IsUnique()
                        .HasDatabaseName("IX_Cities_Name_Country");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WeatherApp.Core.Entities.WeatherCacheEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("WeatherDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique()
                        .HasDatabaseName("IX_WeatherCache_CityId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_WeatherCache_ExpiresAt");

                    b.ToTable("WeatherCache");
                });

            modelBuilder.Entity("WeatherApp.Core.Entities.WeatherCacheEntity", b =>
                {
                    b.HasOne("WeatherApp.Core.Entities.CityEntity", "City")
                        .WithOne("WeatherCache")
                        .HasForeignKey("WeatherApp.Core.Entities.WeatherCacheEntity", "CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherApp.Core.Entities.CityEntity", b =>
                {
                    b.Navigation("WeatherCache");
                });
#pragma warning restore 612, 618
        }
    }
}
